version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/crypto_data.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - crypto_network

  # Streamlit Frontend  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - crypto_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto_network

  # PostgreSQL (optional - for production)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crypto_portfolio
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=crypto_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network

volumes:
  redis_data:
  postgres_data:

networks:
  crypto_network:
    driver: bridge